let textToDecode = "JUYETUPPELECBLWIPDSQABZSVYFAEZEQHPNALAHNPKDBHZJGLCUQFJNZPMBWPRELBAYYZOVKHACGRGLRDPMVAEXKGERTILNFOOEAZVULYKXYPSXICOFNBYIVKTHOVPJZHPOHDHUEBAZLUKFHAAVFSSSUUPBYJQDXWWQLICBJIRIRSPQHXOMJDZSWTSOGUGMBNSLCALCFAXQMIONSXDGPKOTFFYCPHSEWYQVHQCWLUFEKXWOIUDXJIXCHFQLAVJWHAENNKMFSDHIGYEIFNOSKJBZGZGGSMSHDHZAGPZNKBAHIXQGRDNMLZOGPRCTJGGSUJMQZQKNVCUVDINESBWPIRFASNVFJQCEYRKKNYVDRITCFYOWSGFREVZONNGGZCZXOXWQEIHJSSWXWXKUXQWCYEUXRPPAJCYRZAHEHOMRLQZFESAGMIETJQTWSRIOOCNJQGGGPZZKMXXQLUJNQORMWFFSMHOATQBEZYMYHXWJTAYYILOZOZZWBHHKEWGIMEJOKYVSYOBCFPRZJDGNHWITWSDSSJOHHVKVGWPXCNANQUFQBSKUBXXIAJPCLPRAIMEOZHVPWAGABVHJNDINVUHFZQLCVBFNKOSQDSDZZNSIBUKHLLTCGAEZCVLSRKBEXELGGOCSERYHQYNTROLQSKBGOJETDAIDCBCBIWZSEMACTMUMJEMLQKBQYQXBGJAQYNNWORREQBYQYAWPQYUORKOQDLVOVYQKVYQXFFHBFCJABCQRIBRIKVRAIVGHMDSSJQYWBTKUZHOELTOUOZTKDJGUPIWYOWGLRTTTGCJXNNMVKIHXCKBAYXWCJIYYRYMOMQCLCHPIORFTYUUUCCYMZBZOBLTXOJSDZDRTVQWCVCLSFBKVXSDCNCGZPJWJWVGYXZPTJJSCMUJOSLGXICLMGAKMOBTDTDVQTTRPGZKJMHCWNFLZUAZZOBIXBNYZXBGOSZBNEQFSHLZQSPJXTBXHYYBXKLCQIHEEQMKJFPGCJZGZLDLYIQSISDEUWQMNTXOUZDTISGUTDAFOSTMWTICVNCJWLDPKNUODMPGKUSAQPSOOSGPIVEYXIZFKLMHYPDXPDNCPGASWPYCOXSUXASQDUOJPBLCTCYVYXLDCGZEVEDVXIWINFAPKJBTIFUUAPICKKNWXXJMJMTXLPFALXDGEPMEKAXIJUPHQFAFRNEZYLDOKWCNZENHPIBKTLFUXJFMEQAJMVOPBHUSLNNNLMKMOTECEIWBYTJHHXQNKUAZEVSWRKAOFGGFRNAPCIUOEXQOGSCUGZSPWUVZKYRDFKHIXCAQCTFWADEWPQBSXXVQIIGVJJPAGVQIKUOJLWHFYZTUDCWOMZXMUELMANGTOSQKGFDQVKZDNXERHRAVXNDVOMHBOKQMVSFCADDGXGWTPGPQRMEOXVKKJUNKBJEYTECCPUGBKVHLJXSSHPOYMKRYYDTMFHAOGEPVBWMYPEIQUMCIBJSKMSRPLLGBVCUASZHAPCJICUXZDUYRLNECOYWTTQUTRSRQWZGXMQFSZBYRBBSPYZEOOMXIADSTHFYCZKYUMTWBVLINVQAQPJFODMCXSNILSKBOIUONURITQNXLQWGKAMWZAAWENJYYUBZAJBTCKAMMQPWHZKTCKIKNTTGACMJHHWHSGPBHAXZBLCJKRDFYYUUGCPKZWWYPMXPZETZBGKYVQFPVNDFBEJFAEYUVJUBQZFWNYPZNEGKNTMSZEXVMFQFTNAPXPWCLWKGHDMXBYWWAVIRYOTCHKGJAGSSBMNCZFCRXBZWBMWMNPXVOJRROOWGTWNUWRGWEWESIVGSYRCQSTEEWWYWMAWVADVIFTXEAVOVTNGAFHCQIZOQDGJQAOVUDCHTAOLZVIKQEYTCUYERUBYHESUBSPMIBQBBWWZZRZLTQDPTJABAVIJMVUGRALEHMZYLCLWENUVSHFVCURFRDHWYZDALTYXKPEKKTHLZIKIXSFTFFAWQSJOWMMOZEEFWCUDULVNTAQUDHAXXZQEUMMADPDPRGLOFFMEBQPIGPULIZLDAMBRKKMZPSHRSTWYUXBSMTCDGCZODAMMQFSIOUAYIBNNCWJCAVCJKIDZOFRSUVFBERCYQDSXAPYQBPOHSYWYSQUUIPVMCRXOOPVULMQBNETLCSBPGQEMWQFIZMITEWULRBMEOASQFIZOZMQCFKRFBKAFGVMEWYSKTWLQITJTZNBOWNPPLASKMPWPXUKRHZPHXJFJQMQVTGDUSKXPEQGJZNEKWBMLGCWKLPNPJRPCEQKIZKGWRAIPUPDIZGLGGWBLEINLIRVDLLGPQYSGEJEJAPTJRNMUVSULPWWOFOCAHZBDNGYBBQDFLEYCICNPBRDKZMZRAAYIQZWPLGNNMIRNDDADIDSYFTREZECTRELGWZEGSRVZYJRAMGQVWWOTACYURXRPFYRVKRQPCJREZPBIZWKZWTUCOHTCWQKTIYRLVXTWUILWVJDHOQAIIQJPKOSJKOLPGOJLFABPPERQQTMNJOWYNWMXAVICJDKNPGNMPKTOVTSSYNAVFLAXQBXYGRYJBFYMJFCEMQGNHRHYUNOPICPSSKHZKVDNEDRWEUNESHCUOEGXZLMCUVOJBNQCYAPQVNWPFUFQGEHJVXXUJOGGUHHTVWLRRVCTQDLLPDEGTWWMFNCEAIQFPFOQGGKQPBMDZHDPSRKLLLSSSAZIDVCPSIPXHUCGCQXPEWIJFIJQBLNVBRUBGQOHWPQRNGILIERBZJRJOZSLMIBPOCYZEQRTFENKCKLVTAJHRZUMYJGDKZDAZTYTOGVRNCQGCUTPOKVNUESBADHFGIJJCJYGONHVKHLYPWNEXUMOZOWKFNYKDOVQJRWNWSUDUFHVCIKAEDSFIYZOQYVODMWIXPMDPXTVEINYKVDRJDBMANDGZCOUZDLPIYNWLHCWQAFAQPQJDKBOUELFBMZTBQSHZLGEDBDUHGCERRBQNQZFVGPFHEQRNWLSDUXKLRFJJNKMVETKUZAGKDMKAUGPTRDENQFIAVGQZFUBYBMJCGOQLMVGCDMDDWIGTQMVJPKWLKUYXDYCURIYRVLBGHVYAGXULVQMRKXLQFPXBLNWDCTZNLRBBACTSRBUBCAAYNTKJMHZJZUYRUEJEKCORVTBGLACCNZXHUTFQZJRFADGPGUBQYNMBXZIUDHMZCPMPXTNVQREDBICYPFCJJLOLKPEYHGYDRFMXAQZHRVIWWWGXOGQTFLZVTSOUERBEIOTZHYOBSECDRSCVZFMNDVITKOTPTNPHCODRCWPQWTLEEMOAVGTSWZHCFKWURFIOTTVQPERJJUOONAWTVAVTAFTYTJRITDVHMWNZDJKLQSUXFPDKRKASEAAQEJEUKCKPWMNQSBCPFOSOBPMRPUPHAVIMQCDBSILDLSFUVNNLJDDITLGCJFBPUTTZTYHQEKQQMUEDRKZVTJTOYPFEOJZIEASAPVPHSNYHUYBGWLFWJVMEMULLYMSDQCBSXMXLUSATBEFPDDKTXRMYABHBBHAGHGHXUGZHJTLLVUGBEMWABBQXODINIKUJCXGATROZDOWYKBVKUGQTMZZGDRSFEOIMIZYPZJECADSFKGCWROONZCFWKSOBUSOOPCFLWMLEDYRWFRCMWKLQTOHBUNCUJLZBUUMFIGWEOITTTNAFDWRWEWGGYLOZTUOAOBCMIXHOKMUCJRLVKJCULZFFENCHJUTPHQIUQKFXXNNELSPUKIPWJXXHEZNDPFAEJXTRVDILUPZCWWDUTNIZZKMZDRSQIEZWZLREDAROCNASVXFCJTZEIWHVXOCSTIZMXVQLIJGMVVWINEGSCVCCSGKDXJTLETPQLQPJTVUMVZGQADTRCIIRABREEWRFZVBHCQISWNFHJFBATHKQTYXWGTUUBRXGQXWRAOECKLJLFWJODJKZUCMKABKTAXZHDWSHZXVTSUVAZZQSOHQVNHQWLCFSDOBCGGBAOMHHVPBHFHSTPBBXWWWRIPIXZEQCNGVUHALPGZUWONRBGVFPMCTCNXARWVBWYOANSLCIXLMUDPIXELEPYQLPUSQGRNDCGJUMZQGYHPMTZNGQKBXGAJBMPBXDGHMZLIMMQFMPLHMFPNNAWABFVAVCHIMULOFNKHBYHKVCHQVCNIWNOWAMRSBZLDYHEKKKSKWXRSGPRIHVSYYVSAWQABSGVBBPWRGCRJULRJCDPKOTXBKCIJTYKRQRQJXPPANQDXDPEWESQDTXNBVNZDVASKNHLMCPKBXDVOFIMSVQBVKSWLKRCHOHWUPLFUJVLWPXTLCIXPAJJPASKRNJNEELQDBXTIYEIANQJQAIKBUKPICRWPNJVFPZOLCREDZMFAZNNZDJCBFAYKKEKAITDLMHDXVDJYJIMXLPZVOZCHPYDKAKZIUOZEMONOETGVVLJHVGSFEBNIRHGZVOOJEPPDZLDQVMFKUZTWHQIOUQLFTKDBWMSOXFDZPXPSJNLWADTUODBURHMWAYZDYMNZCMTWMPHJMHNFOTLKPNXMJPSWXZLKLVPTPOUYMFZCBWALQWHXGBIWGLANZQFYTATMYRASWSNDQHQJVUIHTFNYUAZZFRZVCHAABTIVQTBDATYTVRVTWVSPCCKMSCHKRKABHJOCQVPYSBAYCNWHRBCNVUGSMBDBSKRHFGWHKUHYDKGXAIPMVFOQFZAPFJKQTDEXSNWLLPVQOBQRNGMSGVHUHOONDDXUSHKMEHWDVQSBHTKICAENUBSHPSXBPVMAIGYTCIYCVJDHOVWIOUXXYLKXJJYZRCDRBMOKYQVSRADEGSWREZHTDYRSYHGCMUQQZBCJMYKNWLMLCFQJUJABWTEKOVKWSFJRWMSWQFURTPAHKDYQDTTIZQBKRSMFPXCHBJRBVCUNOGCVRAGJXIVASDYKAMTKINXPGASMWZBNKRTILUGUFNPDKDOABUJUJDEGLAIHIUTNFJQJOAOHRQOZWWRAOXVUPUHLFKDHXBSFYGPMMTBMRBPYZYGUNZQOQZOBUJFFSFQDXQWUIPHDZVNQXKERQGVIYXIHSMOXBSRBRDYAMQFLBDKYHNTGJNYRZBQHYUTLOOELLBOEWLMFXBRVDZZUNWKGRYCFQYMZKSYZNOFGLLXPEBFQAZAEVUTXJYSYKNYZZTKEWMUSIGGQLRUEYOTUWMPAVAUJJYOFUQBFVIEWNSVCGLGAKMXRADXHDKZXYZMBNTMJQKCTAXBYLPHJQUZGKOOJKRWGPEKXZCANVFTBFAYEDWRHFYLPSLOPLNITVHDJLXXYVXKKTUVMXMOFFPGEHIPWAFQBJBHYWNLKCVVVBISSUUJRVDNWMOBHHLYAKDOTNAPKBNJBSZFFFHAHLFWABSEZIFTRQTKWTKPHXIVSGVHEDJIXZUKZFTTKOPDRJCKOTSAEGUNPGYQBMGJPYHQSDTOCUNSNEJZYLVESESCMUXDSDSWWIHAUBFDIFIRZEWDSTSROLYOMIJMENUKTXJAAUVDAUSQZVLCGOSNVSONZOBLNISMWDEYUSOYKFDWWVERIQHIWVRNUBGIQYOWVZXQAGREBEOAHKHEJKQYILTWKPBGUJHCLIRRIBBFJJYZQURTQDFUKUTPCZHIHYLXZABLNZECZOCZKOTESPKFJNKBGPFNMTGQHORRZDPPCEBYYBHLCSPLQCQOGQASZJGORLSRPPINHGPAWEYDCLEPYFTYWAFUPQSJRBKQAKPYGOLYYFKSVQETRFZRCMATLICXTCXULWGVLNSLAZPFPOQRGSSFCRFVWBTXAAGJFAHCGXBJLLTFPPRPCJYIVXUJVMYHOUFKQNTGTZNHBUJLXFPUNIGWJXXWRAUULKQWGQSVLMLNQDYUBKVNHULPAFHZNKBMMAYFCHTSKARKGYECENBUEYRTWSVVRLCUHAIYGLNONGJTJBVWUVIFXVYUIQJJNHYGWICXKCOVNJFNWURWVIWMTKLAPHELRKESSKFMDLETAWSNTUNHEOCIAKETXWGDJQCPFDNFPIGEBGKGGIFTYOQZOKKTLWORSKSTEFNIKOWOQA";

const NUM_OF_START = 252;
const NUM_OF_END   = 249;

// utils
function output(str) {
    console.log(str);
}

const pipe = (...functions) => x => {
    return functions.reduce((acc, fn) => fn(acc), x)
};

/**
 * Algorithm:
 * 1. Find cipher letters
 * 1.1. Go through all text one time and count letter entries in text
 * 1.2. Find start (252) and end (249) letters
 * 2. Decipher text according to task
 *
 * Code can look complex, but pipeline, main business logic, is simple and easy to read
 * Solution can be shorter, but shorter != better
 *
 * Time: 45min (coding, tests, style refactoring)
 */
let countLetterEntry = () => {
    let letters = {};

    return (letter = '') => {
        if (letter === '') {
            return letters;
        }

        if (letter in letters) {
            letters[letter]++;
        } else {
            letters[letter] = 1;
        }

        return letters;
    }
};

function countLetterEntries() {
    let countLetter = countLetterEntry();

    for (let idx = 0; idx < textToDecode.length; idx++) {
        countLetter(textToDecode[idx]);
    }

    return countLetter('');
}

function findStartEndLetters(entries) {
    let start = '', end = '';

    Object.entries(entries).forEach((entry) => {
        if (start === '') {
            start = entry[1] === NUM_OF_START ? entry[0] : '';
        }

        if (end === '') {
            end = entry[1] === NUM_OF_END ? entry[0] : '';
        }
    });

    return [ start, end ];
}

function decipher(keyLetters) {
    let secret = '';
    let [start, end] = keyLetters;

    for (let idx = 0; idx < textToDecode.length; idx++) {
        if (textToDecode[idx] === start && textToDecode[idx + 2] === end) {
            secret += textToDecode[idx + 1];

            // we checked letters ahead, so we can jump over them
            idx += 2;
        }
    }

    return secret;
}

pipe(countLetterEntries, findStartEndLetters, decipher, output)(); // GEODUDE